# Generated by Django 3.2.7 on 2022-01-18 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='marks',
            new_name='salary',
        ),
        migrations.RemoveField(
            model_name='student',
            name='bf',
        ),
        migrations.RemoveField(
            model_name='student',
            name='gf',
        ),
        migrations.RemoveField(
            model_name='student',
            name='rollno',
        ),
    ]
