# Generated by Django 3.2.7 on 2022-02-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sal', models.FloatField()),
                ('age', models.IntegerField()),
                ('addr', models.CharField(max_length=100)),
            ],
        ),
    ]
